### ISSUE TITLE
Bad version number in setup.py

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/doct#11]

**Comment by danielballan** [comment]
Good catch. If we ever release doct again we'll fix it at that time. I'm not sure that we will.

**Comment by tacaswell** [comment]
This was actually fixed in https://github.com/NSLS-II/doct/commit/bd1fa6c246e553cde0e3245564e0a58926045106 in September however it looks like only the tag was push, not the master branch.  I have just move master up to the latest tag (1.0.5) which has the correct version in setup.py
